image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package
  - deploy

maven-build:
  image: maven:3-jdk-11
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
    - target/*.jar

docker-build:
  stage: package
  before_script:
    - docker info
    - docker login --username $REGISTRY_USERNAME --password $REGISTRY_PASSWORD
  script:
    - docker build -t gabrieljacobina/finance-docker:$CI_PIPELINE_ID .
    - docker push gabrieljacobina/finance-docker:$CI_PIPELINE_ID

deploy:
  image: bitnami/kubectl
  stage: deploy
  tags:
    - k8s-oci
  script:
    - kubectl apply -f finance-deploy.yaml