version: '2.4'
services:
  postgresdb:
    image: postgres:12
    container_name: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRESQL_LOCAL_PORT:$POSTGRESQL_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - postgresdb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:postgresql://postgres:$POSTGRESQL_DOCKER_PORT/$POSTGRES_DATABASE?useSSL=false",
        "spring.datasource.username" : "finance",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation" : "true",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'

volumes:
  db:
