apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance-api
spec:
  selector:
    matchLabels:
      app: finance-api
  replicas: 1
  template:
    metadata:
      labels:
        app: finance-api
    spec:
      containers:
        - name: finance-container-api
          image: gabrieljacobina/finance-docker
          imagePullPolicy: "IfNotPresent"
          env:
          - name: SPRING_APPLICATION_JSON
            value: '{
                      "spring.datasource.url"  : "jdbc:postgresql://10.105.63.188:5432/finance?useSSL=false",
                      "spring.datasource.username" : "finance",
                      "spring.datasource.password" : "root",
                      "spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation" : "true",
                      "spring.jpa.hibernate.ddl-auto" : "update"
                    }'
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: finance-service
spec:
  type: LoadBalancer
  selector:
    app: finance-api
  ports:
  - protocol: TCP
    port: 8080